name: test-py27

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["2.7"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install https://github.com/bboe/coveralls-python/archive/github_actions.zip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test/requirements.txt ]; then pip install -r test/requirements.txt; fi

    - name: Run tests
      run: pytest
